# Default: load .env
set dotenv-load

################################################################
# 🔧 Environment Configuration
#
# Change this to point at the dotenv file you want Just to load.
# Common choices:
#   - ".env"        (default/base)
#   - ".env.local"  (local development)
#   - ".env.dev"    (development server)
#   - ".env.prod"   (production)
################################################################

# set default dotenv file using that variable
set dotenv-filename := ".env.local"
# export it into the environment so recipes can read it
export DOTENV_FILENAME := ".env.local"

################################################################

# Default: use pwsh (PowerShell 7+) for most recipes
set shell := ["pwsh.exe", "-NoLogo", "-Command"]

# So we don't print the command
set quiet := true

_default:
	just --list

alias f01 := f01-show-env
f01-show-env:
	@Write-Output "Active dotenv: $env:DOTENV_FILENAME"

alias f02 := f02-show-all-env
f02-show-all-env:
	Get-ChildItem Env:

alias f1 := f1-create-db-from-backup-no-drop
# Only works with dotenv-filename = .env.local
[doc]
f1-create-db-from-backup-no-drop:
	Write-Output "============================================================"
	Write-Output "🆕 Creating database: ${env:DB_NAME}"
	Write-Output "============================================================"
	psql ${env:DB_URL_ADMIN} -c "CREATE DATABASE ${env:DB_NAME};"
	if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

	Write-Output "============================================================"
	Write-Output "💾 Restoring database ${env:DB_NAME} from backup_${env:DB_NAME}.sql..."
	Write-Output "============================================================"

	# Restore from the most recent backup file (adjust filename if needed)
	psql ${env:DB_URL_TARGET} -f "./backups/northwind_postgres.sql"
	if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

	Write-Output "============================================================"
	Write-Output "🚀 Database ${env:DB_NAME} has been restored from backup 🚀"
	Write-Output "============================================================"